"""create lists and list_items tables

Revision ID: 00d144dec059
Revises: 8f78e740cc84
Create Date: 2025-12-28 19:27:14.629372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d144dec059'
down_revision: Union[str, Sequence[str], None] = '8f78e740cc84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('system_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lists_owner_position', 'lists', ['owner_id', 'position'], unique=False)
    op.create_index(op.f('ix_lists_owner_id'), 'lists', ['owner_id'], unique=False)
    op.create_table('list_items',
    sa.Column('list_id', sa.BigInteger(), nullable=False),
    sa.Column('set_num', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_num'], ['sets.set_num'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('list_id', 'set_num')
    )
    op.create_index('idx_list_items_list_id', 'list_items', ['list_id'], unique=False)
    op.create_index('idx_list_items_set_num', 'list_items', ['set_num'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_list_items_set_num', table_name='list_items')
    op.drop_index('idx_list_items_list_id', table_name='list_items')
    op.drop_table('list_items')
    op.drop_index(op.f('ix_lists_owner_id'), table_name='lists')
    op.drop_index('idx_lists_owner_position', table_name='lists')
    op.drop_table('lists')
    # ### end Alembic commands ###
