"""baseline

Revision ID: 42beccf00f0d
Revises: 
Create Date: 2025-12-13 16:05:26.876826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42beccf00f0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collections', 'set_num',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('collections', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_collections_set_num'), table_name='collections')
    op.drop_index(op.f('idx_collections_user_id'), table_name='collections')
    op.drop_index(op.f('idx_collections_user_type_created'), table_name='collections')
    op.alter_column('reviews', 'set_num',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_reviews_set_num'), table_name='reviews')
    op.drop_constraint(op.f('reviews_user_id_set_num_key'), 'reviews', type_='unique')
    op.create_unique_constraint('reviews_user_set_unique', 'reviews', ['user_id', 'set_num'])
    op.alter_column('sets', 'set_num',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('sets', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('sets', 'theme',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('sets', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('sets', 'image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sets', 'theme',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sets', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('sets', 'set_num',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('reviews_user_set_unique', 'reviews', type_='unique')
    op.create_unique_constraint(op.f('reviews_user_id_set_num_key'), 'reviews', ['user_id', 'set_num'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_reviews_set_num'), 'reviews', ['set_num'], unique=False)
    op.alter_column('reviews', 'set_num',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_collections_user_type_created'), 'collections', ['user_id', 'type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_index(op.f('idx_collections_set_num'), 'collections', ['set_num'], unique=False)
    op.alter_column('collections', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('collections', 'set_num',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
