"""initial schema

Revision ID: 45078d594064
Revises: 
Create Date: 2026-01-25 18:44:52.254847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45078d594064'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sets',
    sa.Column('set_num', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('pieces', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('set_num')
    )
    op.create_index(op.f('ix_sets_name'), 'sets', ['name'], unique=False)
    op.create_index(op.f('ix_sets_theme'), 'sets', ['theme'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('system_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lists_owner_position', 'lists', ['owner_id', 'position'], unique=False)
    op.create_index(op.f('ix_lists_owner_id'), 'lists', ['owner_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('set_num', sa.String(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rating IS NULL OR (rating >= 0.5 AND rating <= 5.0)', name='reviews_rating_check'),
    sa.ForeignKeyConstraint(['set_num'], ['sets.set_num'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'set_num', name='reviews_user_set_unique')
    )
    op.create_index('idx_reviews_set_num', 'reviews', ['set_num'], unique=False)
    op.create_index(op.f('ix_reviews_set_num'), 'reviews', ['set_num'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('list_items',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('set_num', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_num'], ['sets.set_num'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('list_id', 'set_num')
    )
    op.create_index('idx_list_items_list_id', 'list_items', ['list_id'], unique=False)
    op.create_index('idx_list_items_set_num', 'list_items', ['set_num'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_list_items_set_num', table_name='list_items')
    op.drop_index('idx_list_items_list_id', table_name='list_items')
    op.drop_table('list_items')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_set_num'), table_name='reviews')
    op.drop_index('idx_reviews_set_num', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_lists_owner_id'), table_name='lists')
    op.drop_index('idx_lists_owner_position', table_name='lists')
    op.drop_table('lists')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sets_theme'), table_name='sets')
    op.drop_index(op.f('ix_sets_name'), table_name='sets')
    op.drop_table('sets')
    # ### end Alembic commands ###
