"""add_msrp_and_offers_table

Revision ID: 4d4340120fda
Revises: b1f2afca2090
Create Date: 2026-03-06 09:08:56.784445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4340120fda'
down_revision: Union[str, Sequence[str], None] = 'b1f2afca2090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_num', sa.String(), nullable=False),
    sa.Column('store', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='USD', nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('asin', sa.String(), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_set_num'), 'offers', ['set_num'], unique=False)
    op.add_column('sets', sa.Column('retail_price', sa.Float(), nullable=True))
    op.add_column('sets', sa.Column('retail_currency', sa.String(length=8), server_default='USD', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sets', 'retail_currency')
    op.drop_column('sets', 'retail_price')
    op.drop_index(op.f('ix_offers_set_num'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
