"""add_deal_alerts

Revision ID: b1f2afca2090
Revises: 4890e56a84c2
Create Date: 2026-03-06 09:04:43.174436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f2afca2090'
down_revision: Union[str, Sequence[str], None] = '4890e56a84c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('set_num', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("alert_type IN ('price_drop', 'retiring')", name='deal_alerts_type_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'set_num', 'alert_type', name='deal_alerts_user_set_type_unique')
    )
    op.create_index(op.f('ix_deal_alerts_set_num'), 'deal_alerts', ['set_num'], unique=False)
    op.create_index(op.f('ix_deal_alerts_user_id'), 'deal_alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deal_alerts_user_id'), table_name='deal_alerts')
    op.drop_index(op.f('ix_deal_alerts_set_num'), table_name='deal_alerts')
    op.drop_table('deal_alerts')
    # ### end Alembic commands ###
