"""add_review_votes

Revision ID: c2707c4eca0f
Revises: 5db7b012b0ca
Create Date: 2026-03-06 07:43:53.754701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2707c4eca0f'
down_revision: Union[str, Sequence[str], None] = '5db7b012b0ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("vote_type IN ('up', 'down')", name='review_votes_type_check'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'user_id', name='review_votes_review_user_unique')
    )
    op.create_index(op.f('ix_review_votes_review_id'), 'review_votes', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_votes_user_id'), 'review_votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_votes_user_id'), table_name='review_votes')
    op.drop_index(op.f('ix_review_votes_review_id'), table_name='review_votes')
    op.drop_table('review_votes')
    # ### end Alembic commands ###
