"""add affiliate click tracking fields

Revision ID: fa192844a752
Revises: 1735362fe962
Create Date: 2026-03-04 07:32:26.641089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa192844a752'
down_revision: Union[str, Sequence[str], None] = '1735362fe962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_clicks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('set_num', sa.String(), nullable=False),
    sa.Column('store', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('offer_rank', sa.Integer(), nullable=True),
    sa.Column('page_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_clicks_set_num'), 'affiliate_clicks', ['set_num'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_store'), 'affiliate_clicks', ['store'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_user_id'), 'affiliate_clicks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affiliate_clicks_user_id'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_store'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_set_num'), table_name='affiliate_clicks')
    op.drop_table('affiliate_clicks')
    # ### end Alembic commands ###
