"""add brickset enrichment fields to sets

Revision ID: fbe84f4db00a
Revises: c751cabdf740
Create Date: 2026-03-06 18:13:15.525951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe84f4db00a'
down_revision: Union[str, Sequence[str], None] = 'c751cabdf740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('description', sa.String(), nullable=True))
    op.add_column('sets', sa.Column('subtheme', sa.String(), nullable=True))
    op.add_column('sets', sa.Column('minifigs', sa.Integer(), nullable=True))
    op.add_column('sets', sa.Column('age_min', sa.Integer(), nullable=True))
    op.add_column('sets', sa.Column('age_max', sa.Integer(), nullable=True))
    op.add_column('sets', sa.Column('dimensions_height', sa.Float(), nullable=True))
    op.add_column('sets', sa.Column('dimensions_width', sa.Float(), nullable=True))
    op.add_column('sets', sa.Column('dimensions_depth', sa.Float(), nullable=True))
    op.add_column('sets', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('sets', sa.Column('barcode_ean', sa.String(), nullable=True))
    op.add_column('sets', sa.Column('barcode_upc', sa.String(), nullable=True))
    op.add_column('sets', sa.Column('launch_date', sa.String(), nullable=True))
    op.add_column('sets', sa.Column('exit_date', sa.String(), nullable=True))
    op.create_index(op.f('ix_sets_subtheme'), 'sets', ['subtheme'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sets_subtheme'), table_name='sets')
    op.create_index(op.f('ix_sets_retirement_status'), 'sets', ['retirement_status'], unique=False)
    op.create_index(op.f('ix_sets_first_seen_at'), 'sets', ['first_seen_at'], unique=False)
    op.drop_column('sets', 'exit_date')
    op.drop_column('sets', 'launch_date')
    op.drop_column('sets', 'barcode_upc')
    op.drop_column('sets', 'barcode_ean')
    op.drop_column('sets', 'weight_kg')
    op.drop_column('sets', 'dimensions_depth')
    op.drop_column('sets', 'dimensions_width')
    op.drop_column('sets', 'dimensions_height')
    op.drop_column('sets', 'age_max')
    op.drop_column('sets', 'age_min')
    op.drop_column('sets', 'minifigs')
    op.drop_column('sets', 'subtheme')
    op.drop_column('sets', 'description')
    # ### end Alembic commands ###
